// Code generated by Wire. DO NOT EDIT.

/**
go:generate go run github.com/google/wire/cmd/wire
**/
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos-shop/internal/biz"
	"kratos-shop/internal/conf"
	"kratos-shop/internal/data"
	"kratos-shop/internal/server"
	"kratos-shop/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewGormDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)

	studentRepo := data.NewStudentRepo(dataData, logger)
	studentUsecase := biz.NewStudentUsercase(studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase)

	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService,studentService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
